/* data.ts — Mock data for JobPA v2 landing page demo */

export interface Job {
  id: string;
  title: string;
  company: string;
  companyLogo: string;
  location: string;
  salary: string;
  salaryRaw: [number, number];
  interviewProb: number;
  matchScore: number;
  sources: string[];
  tags: string[];
  industry: string;
  postedDate: string;
  description: string;
  applyLink?: string;
}

export interface Consultant {
  id: string;
  name: string;
  avatar: string;
  title: string;
  company: string;
  industry: string;
  tags: string[];
  rating: number;
  reviews: number;
  sessions: number;
  price: number;
  currency: string;
  languages: string[];
  available: boolean;
}

export interface Course {
  id: string;
  title: string;
  instructor: string;
  type: 'workshop' | 'seminar' | 'class';
  date: string;
  image: string;
  tags: string[];
  seats: number;
  seatsLeft: number;
  price: number;
  currency: string;
}

export interface TrendingSkill {
  name: string;
  growth: string;
  hot: boolean;
}

export const MARKET_STATS = {
  totalJobs: 2847,
  avgSalary: 'SGD 8,500',
  hiringGrowth: 12,
};

export const TRENDING_SKILLS: TrendingSkill[] = [
  { name: 'AI / Machine Learning', growth: '+38%', hot: true },
  { name: 'Product Management', growth: '+24%', hot: true },
  { name: 'Data Engineering', growth: '+21%', hot: false },
  { name: 'Cloud Architecture (AWS)', growth: '+19%', hot: false },
  { name: 'Growth Marketing', growth: '+17%', hot: true },
  { name: 'Cybersecurity', growth: '+15%', hot: false },
  { name: 'UX Research', growth: '+12%', hot: false },
];

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Product Marketing Manager',
    company: 'Grab',
    companyLogo: 'https://logo.clearbit.com/grab.com',
    location: 'Singapore',
    salary: 'SGD 8,000 – 12,000',
    salaryRaw: [8000, 12000],
    interviewProb: 87,
    matchScore: 92,
    sources: ['MCF', 'LinkedIn'],
    tags: ['Product Marketing', 'Go-to-Market', 'B2C', 'Fintech'],
    industry: 'technology',
    postedDate: '2 days ago',
    description: 'Lead product marketing for Grab Financial Group, developing go-to-market strategies for new financial products across SEA. You will work closely with product, sales, and regional teams to drive adoption and growth.',
  },
  {
    id: '2',
    title: 'Customer Success Manager',
    company: 'Salesforce',
    companyLogo: 'https://logo.clearbit.com/salesforce.com',
    location: 'Singapore',
    salary: 'SGD 7,500 – 10,000',
    salaryRaw: [7500, 10000],
    interviewProb: 79,
    matchScore: 85,
    sources: ['LinkedIn', 'Company'],
    tags: ['Customer Success', 'SaaS', 'CRM', 'Enterprise'],
    industry: 'technology',
    postedDate: '1 day ago',
    description: 'Own the success of a portfolio of enterprise accounts, driving adoption, renewal, and expansion. You will serve as a trusted advisor and escalation point for key customers in the APAC region.',
  },
  {
    id: '3',
    title: 'Marketing Analytics Lead',
    company: 'Sea Group',
    companyLogo: 'https://logo.clearbit.com/sea.com',
    location: 'Singapore',
    salary: 'SGD 9,000 – 13,000',
    salaryRaw: [9000, 13000],
    interviewProb: 72,
    matchScore: 80,
    sources: ['MCF', 'LinkedIn'],
    tags: ['Analytics', 'SQL', 'Python', 'E-commerce'],
    industry: 'e-commerce',
    postedDate: '3 days ago',
    description: 'Drive data-driven marketing decisions for Shopee\'s regional campaigns. You will build dashboards, run attribution models, and partner with marketing teams to optimize spend across channels.',
  },
  {
    id: '4',
    title: 'Pre-Sales Consultant',
    company: 'SAP',
    companyLogo: 'https://logo.clearbit.com/sap.com',
    location: 'Singapore',
    salary: 'SGD 8,500 – 11,500',
    salaryRaw: [8500, 11500],
    interviewProb: 65,
    matchScore: 74,
    sources: ['LinkedIn', 'Company'],
    tags: ['Pre-Sales', 'ERP', 'B2B', 'Enterprise Software'],
    industry: 'technology',
    postedDate: '5 days ago',
    description: 'Support the sales team with technical demonstrations and solution architecture for SAP S/4HANA. You will engage with C-level stakeholders and translate business requirements into technical solutions.',
  },
  {
    id: '5',
    title: 'Senior Data Analyst',
    company: 'DBS Bank',
    companyLogo: 'https://logo.clearbit.com/dbs.com',
    location: 'Singapore',
    salary: 'SGD 7,000 – 10,500',
    salaryRaw: [7000, 10500],
    interviewProb: 83,
    matchScore: 88,
    sources: ['MCF', 'LinkedIn', 'Company'],
    tags: ['Data Analysis', 'SQL', 'Tableau', 'Banking'],
    industry: 'finance',
    postedDate: '1 day ago',
    description: 'Join DBS\'s digital banking analytics team to derive insights from customer transaction data. You will build models to improve customer segmentation, product recommendations, and risk scoring.',
  },
  {
    id: '6',
    title: 'Growth Marketing Manager',
    company: 'Lazada',
    companyLogo: 'https://logo.clearbit.com/lazada.com',
    location: 'Singapore',
    salary: 'SGD 6,500 – 9,500',
    salaryRaw: [6500, 9500],
    interviewProb: 76,
    matchScore: 82,
    sources: ['Indeed', 'LinkedIn'],
    tags: ['Growth', 'Performance Marketing', 'SEA', 'E-commerce'],
    industry: 'e-commerce',
    postedDate: '4 days ago',
    description: 'Drive user acquisition and retention through paid and organic channels for Lazada Singapore. You will manage a significant media budget and work with regional teams on campaign strategy.',
  },
  {
    id: '7',
    title: 'Product Manager — Payments',
    company: 'Stripe',
    companyLogo: 'https://logo.clearbit.com/stripe.com',
    location: 'Singapore',
    salary: 'SGD 12,000 – 18,000',
    salaryRaw: [12000, 18000],
    interviewProb: 58,
    matchScore: 70,
    sources: ['LinkedIn', 'Company'],
    tags: ['Product Management', 'Payments', 'Fintech', 'API'],
    industry: 'technology',
    postedDate: '6 days ago',
    description: 'Own the product roadmap for Stripe\'s payment infrastructure in APAC. You will work with engineering, design, and business teams to launch new payment methods and improve conversion rates.',
  },
  {
    id: '8',
    title: 'Business Development Manager',
    company: 'Gojek',
    companyLogo: 'https://logo.clearbit.com/gojek.com',
    location: 'Singapore',
    salary: 'SGD 7,000 – 10,000',
    salaryRaw: [7000, 10000],
    interviewProb: 71,
    matchScore: 77,
    sources: ['MCF', 'Indeed'],
    tags: ['Business Development', 'Partnerships', 'Super App', 'SEA'],
    industry: 'technology',
    postedDate: '2 days ago',
    description: 'Identify and close strategic partnerships for GoTo Financial across SEA. You will negotiate commercial terms, manage partner relationships, and drive revenue growth through the ecosystem.',
  },
  {
    id: '9',
    title: 'UX Research Lead',
    company: 'Shopback',
    companyLogo: 'https://logo.clearbit.com/shopback.com',
    location: 'Singapore',
    salary: 'SGD 7,500 – 11,000',
    salaryRaw: [7500, 11000],
    interviewProb: 68,
    matchScore: 75,
    sources: ['LinkedIn', 'Company'],
    tags: ['UX Research', 'User Testing', 'Qualitative Research', 'Cashback'],
    industry: 'e-commerce',
    postedDate: '1 week ago',
    description: 'Lead user research initiatives to inform product decisions at Shopback. You will conduct usability studies, user interviews, and surveys to understand shopper behavior across markets.',
  },
  {
    id: '10',
    title: 'Investment Analyst',
    company: 'Temasek',
    companyLogo: 'https://logo.clearbit.com/temasek.com.sg',
    location: 'Singapore',
    salary: 'SGD 9,000 – 14,000',
    salaryRaw: [9000, 14000],
    interviewProb: 52,
    matchScore: 63,
    sources: ['MCF', 'LinkedIn'],
    tags: ['Investment', 'Financial Modeling', 'Due Diligence', 'Private Equity'],
    industry: 'finance',
    postedDate: '3 days ago',
    description: 'Evaluate investment opportunities across technology and consumer sectors for Temasek\'s portfolio. You will build financial models, conduct due diligence, and present investment recommendations.',
  },
  {
    id: '11',
    title: 'Cloud Solutions Architect',
    company: 'AWS',
    companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
    location: 'Singapore',
    salary: 'SGD 14,000 – 20,000',
    salaryRaw: [14000, 20000],
    interviewProb: 61,
    matchScore: 72,
    sources: ['LinkedIn', 'Company'],
    tags: ['AWS', 'Cloud Architecture', 'Solutions Engineering', 'Enterprise'],
    industry: 'technology',
    postedDate: '5 days ago',
    description: 'Help enterprise customers design and implement cloud architectures on AWS. You will serve as a trusted technical advisor, running workshops and proof-of-concepts to accelerate cloud adoption.',
  },
  {
    id: '12',
    title: 'HR Business Partner',
    company: 'Singtel',
    companyLogo: 'https://logo.clearbit.com/singtel.com',
    location: 'Singapore',
    salary: 'SGD 6,000 – 8,500',
    salaryRaw: [6000, 8500],
    interviewProb: 74,
    matchScore: 79,
    sources: ['MCF', 'LinkedIn'],
    tags: ['HR', 'Talent Management', 'Organizational Development', 'Telco'],
    industry: 'technology',
    postedDate: '2 days ago',
    description: 'Partner with business leaders to drive HR strategy, talent acquisition, and organizational development at Singtel. You will manage performance cycles, succession planning, and employee engagement.',
  },
  {
    id: '13',
    title: 'Digital Marketing Specialist',
    company: 'Carousell',
    companyLogo: 'https://logo.clearbit.com/carousell.com',
    location: 'Singapore',
    salary: 'SGD 4,500 – 6,500',
    salaryRaw: [4500, 6500],
    interviewProb: 81,
    matchScore: 86,
    sources: ['MCF', 'Indeed', 'LinkedIn'],
    tags: ['Digital Marketing', 'Social Media', 'Content', 'Marketplace'],
    industry: 'e-commerce',
    postedDate: '1 day ago',
    description: 'Execute digital marketing campaigns across social, search, and display channels for Carousell. You will manage content calendars, run A/B tests, and report on campaign performance.',
  },
  {
    id: '14',
    title: 'Operations Manager',
    company: 'FedEx',
    companyLogo: 'https://logo.clearbit.com/fedex.com',
    location: 'Singapore',
    salary: 'SGD 6,500 – 9,000',
    salaryRaw: [6500, 9000],
    interviewProb: 66,
    matchScore: 71,
    sources: ['MCF', 'Company'],
    tags: ['Operations', 'Logistics', 'Supply Chain', 'Process Improvement'],
    industry: 'technology',
    postedDate: '4 days ago',
    description: 'Oversee daily operations for FedEx\'s Singapore hub, managing a team of 50+ staff. You will drive process improvements, ensure SLA compliance, and manage vendor relationships.',
  },
  {
    id: '15',
    title: 'Quantitative Analyst',
    company: 'Standard Chartered',
    companyLogo: 'https://logo.clearbit.com/sc.com',
    location: 'Singapore',
    salary: 'SGD 10,000 – 16,000',
    salaryRaw: [10000, 16000],
    interviewProb: 55,
    matchScore: 67,
    sources: ['LinkedIn', 'Company'],
    tags: ['Quant', 'Python', 'Risk Modeling', 'Banking'],
    industry: 'finance',
    postedDate: '1 week ago',
    description: 'Develop quantitative models for market risk, credit risk, and portfolio optimization at StanChart. You will work with large datasets and implement models in Python and R.',
  },
  {
    id: '16',
    title: 'Content Strategy Manager',
    company: 'Canva',
    companyLogo: 'https://logo.clearbit.com/canva.com',
    location: 'Singapore',
    salary: 'SGD 7,000 – 10,000',
    salaryRaw: [7000, 10000],
    interviewProb: 77,
    matchScore: 83,
    sources: ['LinkedIn', 'Indeed'],
    tags: ['Content Strategy', 'SEO', 'Brand', 'SaaS'],
    industry: 'technology',
    postedDate: '3 days ago',
    description: 'Define and execute content strategy for Canva\'s APAC markets. You will oversee editorial calendars, manage a team of writers, and ensure content aligns with brand voice and business goals.',
  },
  {
    id: '17',
    title: 'Compliance Officer',
    company: 'MAS',
    companyLogo: 'https://logo.clearbit.com/mas.gov.sg',
    location: 'Singapore',
    salary: 'SGD 7,500 – 11,000',
    salaryRaw: [7500, 11000],
    interviewProb: 63,
    matchScore: 69,
    sources: ['MCF'],
    tags: ['Compliance', 'Regulatory', 'Fintech', 'AML'],
    industry: 'finance',
    postedDate: '6 days ago',
    description: 'Ensure regulatory compliance for fintech firms under MAS supervision. You will review license applications, conduct on-site inspections, and provide guidance on regulatory requirements.',
  },
  {
    id: '18',
    title: 'Software Engineer — Backend',
    company: 'Tokopedia',
    companyLogo: 'https://logo.clearbit.com/tokopedia.com',
    location: 'Singapore',
    salary: 'SGD 8,000 – 13,000',
    salaryRaw: [8000, 13000],
    interviewProb: 70,
    matchScore: 76,
    sources: ['LinkedIn', 'Indeed'],
    tags: ['Go', 'Microservices', 'Kubernetes', 'E-commerce'],
    industry: 'e-commerce',
    postedDate: '2 days ago',
    description: 'Build and scale backend services for Tokopedia\'s marketplace platform. You will design microservices in Go, optimize database queries, and ensure high availability for millions of daily users.',
  },
  {
    id: '19',
    title: 'Account Executive — Enterprise',
    company: 'HubSpot',
    companyLogo: 'https://logo.clearbit.com/hubspot.com',
    location: 'Singapore',
    salary: 'SGD 8,000 – 14,000',
    salaryRaw: [8000, 14000],
    interviewProb: 73,
    matchScore: 80,
    sources: ['LinkedIn', 'Company'],
    tags: ['Sales', 'SaaS', 'CRM', 'Enterprise'],
    industry: 'technology',
    postedDate: '4 days ago',
    description: 'Drive new business for HubSpot\'s enterprise segment in APAC. You will manage a pipeline of mid-market and enterprise accounts, run product demos, and close complex multi-year deals.',
  },
  {
    id: '20',
    title: 'Regional Brand Manager',
    company: 'P&G',
    companyLogo: 'https://logo.clearbit.com/pg.com',
    location: 'Singapore',
    salary: 'SGD 7,000 – 10,500',
    salaryRaw: [7000, 10500],
    interviewProb: 69,
    matchScore: 75,
    sources: ['MCF', 'LinkedIn', 'Indeed'],
    tags: ['Brand Management', 'FMCG', 'Marketing Strategy', 'SEA'],
    industry: 'technology',
    postedDate: '1 week ago',
    description: 'Own the brand P&L for a key P&G portfolio brand across SEA markets. You will develop brand strategy, manage agency relationships, and lead integrated marketing campaigns.',
  },
];

export const MOCK_CONSULTANTS: Consultant[] = [
  {
    id: 'c1',
    name: 'Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&h=100&fit=crop&crop=face',
    title: 'Ex-Google PM · Career Coach',
    company: 'Google → Independent',
    industry: 'Technology',
    tags: ['Product Management', 'Tech Interviews', 'FAANG Prep', 'Resume Review'],
    rating: 4.9,
    reviews: 127,
    sessions: 340,
    price: 150,
    currency: 'SGD',
    languages: ['English', 'Mandarin'],
    available: true,
  },
  {
    id: 'c2',
    name: 'James Lim',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    title: 'VP Talent Acquisition · DBS',
    company: 'DBS Bank',
    industry: 'Finance',
    tags: ['Banking Careers', 'Interview Prep', 'Salary Negotiation', 'Finance'],
    rating: 4.8,
    reviews: 89,
    sessions: 210,
    price: 120,
    currency: 'SGD',
    languages: ['English', 'Mandarin', 'Bahasa'],
    available: true,
  },
  {
    id: 'c3',
    name: 'Priya Nair',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face',
    title: 'Immigration Lawyer · SG EP/PR',
    company: 'Nair & Associates',
    industry: 'Legal',
    tags: ['Employment Pass', 'PR Application', 'S Pass', 'Work Visa'],
    rating: 4.95,
    reviews: 203,
    sessions: 520,
    price: 200,
    currency: 'SGD',
    languages: ['English', 'Tamil', 'Hindi'],
    available: true,
  },
  {
    id: 'c4',
    name: 'Min-jun Park',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    title: 'Ex-McKinsey · Strategy Consultant',
    company: 'McKinsey → Independent',
    industry: 'Consulting',
    tags: ['Consulting Interviews', 'Case Prep', 'Strategy', 'MBB'],
    rating: 4.85,
    reviews: 156,
    sessions: 280,
    price: 180,
    currency: 'SGD',
    languages: ['English', 'Korean', 'Japanese'],
    available: false,
  },
  {
    id: 'c5',
    name: 'Alicia Wong',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
    title: 'Head of Growth · Startup Advisor',
    company: 'Carousell → Advisor',
    industry: 'Technology',
    tags: ['Growth Marketing', 'Startup Careers', 'Digital Marketing', 'SEA'],
    rating: 4.7,
    reviews: 74,
    sessions: 180,
    price: 100,
    currency: 'SGD',
    languages: ['English', 'Mandarin'],
    available: true,
  },
  {
    id: 'c6',
    name: 'David Tan',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    title: 'CFO · Finance Career Coach',
    company: 'Temasek → Independent',
    industry: 'Finance',
    tags: ['Finance Careers', 'CFA Prep', 'Investment Banking', 'PE/VC'],
    rating: 4.9,
    reviews: 112,
    sessions: 295,
    price: 160,
    currency: 'SGD',
    languages: ['English', 'Mandarin'],
    available: true,
  },
];

export const MOCK_COURSES: Course[] = [
  {
    id: 'co1',
    title: 'AI-Proof Your Resume: ATS Optimization Workshop',
    instructor: 'Sarah Chen',
    type: 'workshop',
    date: '2025-04-15',
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=400&h=200&fit=crop',
    tags: ['Resume', 'ATS', 'AI Tools', 'Job Search'],
    seats: 30,
    seatsLeft: 7,
    price: 0,
    currency: 'SGD',
  },
  {
    id: 'co2',
    title: 'Crack the Singapore Employment Pass: EP & PR Guide',
    instructor: 'Priya Nair',
    type: 'seminar',
    date: '2025-04-20',
    image: 'https://images.unsplash.com/photo-1565967511849-76a60a516170?w=400&h=200&fit=crop',
    tags: ['EP', 'PR', 'Immigration', 'Singapore'],
    seats: 50,
    seatsLeft: 23,
    price: 0,
    currency: 'SGD',
  },
  {
    id: 'co3',
    title: 'Product Management Interview Bootcamp',
    instructor: 'Sarah Chen',
    type: 'class',
    date: '2025-05-01',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=200&fit=crop',
    tags: ['PM', 'Interview', 'FAANG', 'Case Study'],
    seats: 20,
    seatsLeft: 4,
    price: 299,
    currency: 'SGD',
  },
  {
    id: 'co4',
    title: 'Salary Negotiation Masterclass for Tech Roles',
    instructor: 'James Lim',
    type: 'workshop',
    date: '2025-04-28',
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&h=200&fit=crop',
    tags: ['Salary', 'Negotiation', 'Tech', 'Compensation'],
    seats: 40,
    seatsLeft: 0,
    price: 89,
    currency: 'SGD',
  },
  {
    id: 'co5',
    title: 'McKinsey Case Interview: Frameworks & Practice',
    instructor: 'Min-jun Park',
    type: 'class',
    date: '2025-05-10',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=200&fit=crop',
    tags: ['Consulting', 'Case Interview', 'MBB', 'Frameworks'],
    seats: 15,
    seatsLeft: 9,
    price: 399,
    currency: 'SGD',
  },
  {
    id: 'co6',
    title: 'Growth Marketing in SEA: From Zero to Scale',
    instructor: 'Alicia Wong',
    type: 'seminar',
    date: '2025-04-18',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=200&fit=crop',
    tags: ['Growth', 'Marketing', 'SEA', 'Digital'],
    seats: 60,
    seatsLeft: 31,
    price: 0,
    currency: 'SGD',
  },
  {
    id: 'co7',
    title: 'Finance Career Accelerator: CFA & Investment Banking',
    instructor: 'David Tan',
    type: 'class',
    date: '2025-05-05',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=200&fit=crop',
    tags: ['Finance', 'CFA', 'Investment Banking', 'Modelling'],
    seats: 25,
    seatsLeft: 12,
    price: 249,
    currency: 'SGD',
  },
  {
    id: 'co8',
    title: 'LinkedIn Profile Optimization for APAC Job Market',
    instructor: 'Alicia Wong',
    type: 'workshop',
    date: '2025-04-12',
    image: 'https://images.unsplash.com/photo-1611944212129-29977ae1398c?w=400&h=200&fit=crop',
    tags: ['LinkedIn', 'Personal Brand', 'Job Search', 'Profile'],
    seats: 35,
    seatsLeft: 18,
    price: 0,
    currency: 'SGD',
  },
];
